# Generated by Django 5.2.6 on 2025-09-13 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('end_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('exposure', models.BigIntegerField(help_text='Exposure per week')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depot_name', models.CharField(max_length=255)),
                ('number_of_standing_lanes', models.BigIntegerField()),
                ('number_of_cleaning_lanes', models.BigIntegerField()),
                ('number_of_maintainance_lanes', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('day', models.BigIntegerField()),
                ('train_number', models.BigIntegerField()),
                ('starting_point', models.CharField(max_length=255)),
                ('starting_time', models.DateTimeField()),
                ('ending_point', models.CharField(blank=True, max_length=255, null=True)),
                ('ending_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Trainset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_id', models.BigIntegerField()),
                ('total_distance_travelled', models.BigIntegerField()),
                ('distance_travelled_since_last_service', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CleaningBay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bay_number', models.BigIntegerField()),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.depot')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionBay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane_number', models.BigIntegerField()),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.depot')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionBayEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_id', models.BigIntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('bay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.inspectionbay')),
            ],
        ),
        migrations.CreateModel(
            name='MaintainanceBay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane_number', models.BigIntegerField()),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.depot')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingBay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane_number', models.BigIntegerField()),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.depot')),
            ],
        ),
        migrations.CreateModel(
            name='DesignedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.role')),
            ],
        ),
        migrations.CreateModel(
            name='TrainScheduled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.timetable')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.trainset')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingTrainEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterd', models.DateTimeField()),
                ('exited', models.DateTimeField()),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.parkingbay')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.trainset')),
            ],
        ),
        migrations.CreateModel(
            name='MaintainanceTrainEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterd', models.DateTimeField()),
                ('exited', models.DateTimeField()),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.maintainancebay')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.trainset')),
            ],
        ),
        migrations.CreateModel(
            name='CleaningTrainEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterd', models.DateTimeField()),
                ('exited', models.DateTimeField()),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cleaningbay')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.trainset')),
            ],
        ),
        migrations.CreateModel(
            name='Branded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.brandingdeal')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.trainset')),
            ],
        ),
    ]
