# Generated by Django 5.2.6 on 2025-09-13 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designeduser',
            name='depot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.depot'),
        ),
    ]
