# Generated by Django 5.2.6 on 2025-09-13 11:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_designeduser_depot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionbayentry',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='inspectionbayentry',
            name='start_time',
        ),
        migrations.AddField(
            model_name='cleaningtrainentry',
            name='scheduledEnd',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cleaningtrainentry',
            name='scheduledStart',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inspectionbayentry',
            name='enterd',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionbayentry',
            name='exited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionbayentry',
            name='scheduledEnd',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inspectionbayentry',
            name='scheduledStart',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='maintainancetrainentry',
            name='scheduledEnd',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='maintainancetrainentry',
            name='scheduledStart',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='parkingtrainentry',
            name='scheduledEnd',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='parkingtrainentry',
            name='scheduledStart',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cleaningtrainentry',
            name='enterd',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cleaningtrainentry',
            name='exited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintainancetrainentry',
            name='enterd',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintainancetrainentry',
            name='exited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingtrainentry',
            name='enterd',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingtrainentry',
            name='exited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
