# Generated by Django 5.2.6 on 2025-09-13 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_inspectionbayentry_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionbayentry',
            name='bay',
        ),
        migrations.RemoveField(
            model_name='inspectionbayentry',
            name='train_id',
        ),
        migrations.AddField(
            model_name='inspectionbayentry',
            name='lane',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.inspectionbay'),
        ),
        migrations.AddField(
            model_name='inspectionbayentry',
            name='train',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.trainset'),
        ),
    ]
