# Generated by Django 5.2.6 on 2025-09-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_inspectionbayentry_bay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designeduser',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
