# Generated by Django 5.2.6 on 2025-09-16 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_designeduser_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.trainset')),
            ],
        ),
    ]
