# Generated by Django 5.2.6 on 2025-09-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_jobcards'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcards',
            name='how_closed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
